version: "3"

services:

  jenkins:
    image: jenkinsci/blueocean
    user: root
    container_name: jenkins
    ports:
      - "7070:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./home:/home
      - /var/run/docker.sock:/var/run/docker.sock

  selenium-hub:
    image: selenium/hub:3.141.59-zinc
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - hotels-test-network

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  hotels-tests:
    build:
      dockerfile: Dockerfile
      context: .
    # image: amiroous/python-tests
    depends_on:
      - selenium-hub
    links:
      - selenium-hub:hub
    networks:
      - hotels-test-network
    command: ["python", "-m" , "pytest", "-m", "health_test"]

networks:
  hotels-test-network:

volumes:
  jenkins_home: